SLUG_REGEX = '^[-a-zA-Z0-9_]+$'
SLUG_ERROR = 'Slug может содержать только буквы, цифры, дефисы и подчеркивания'

CATEGORY_NAME_MAX_LENGTH = 256
CATEGORY_SLUG_MAX_LENGTH = 50

GENRE_NAME_MAX_LENGTH = 256
GENRE_SLUG_MAX_LENGTH = 50

TITLE_NAME_MAX_LENGTH = 256

REVIEW_SCORE_MIN = 1
REVIEW_SCORE_MAX = 10