# Generated by Django 5.1.1 on 2025-07-13 16:42

from django.db import migrations, models

import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_comment_review_unique_title_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.models.validate_current_year], verbose_name='Год выпуска'),
        ),
    ]
